version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/packages/eslint-config/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/packages/eslint-config-cypress/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/packages/eslint-config-jest/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/packages/eslint-config-react/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/packages/eslint-config-react-native/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/packages/eslint-config-typescript/"
    update_schedule: "daily"